// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1RwVTTF9aFRtgjEeJzjlLoCGWREAiESI',
    appId: '1:978477640072:web:e66011361614d1f648b23d',
    messagingSenderId: '978477640072',
    projectId: 'fixmyarea-capstone',
    authDomain: 'fixmyarea-capstone.firebaseapp.com',
    storageBucket: 'fixmyarea-capstone.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAw6_4D5XRGBzDquHqhTHWa5EtkpOVQhp8',
    appId: '1:978477640072:ios:c9e07a4967bdd44348b23d',
    messagingSenderId: '978477640072',
    projectId: 'fixmyarea-capstone',
    storageBucket: 'fixmyarea-capstone.firebasestorage.app',
    iosBundleId: 'com.example.fixMyArea',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC1RwVTTF9aFRtgjEeJzjlLoCGWREAiESI',
    appId: '1:978477640072:web:8b4165a2082b33f248b23d',
    messagingSenderId: '978477640072',
    projectId: 'fixmyarea-capstone',
    authDomain: 'fixmyarea-capstone.firebaseapp.com',
    storageBucket: 'fixmyarea-capstone.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAw6_4D5XRGBzDquHqhTHWa5EtkpOVQhp8',
    appId: '1:978477640072:ios:c9e07a4967bdd44348b23d',
    messagingSenderId: '978477640072',
    projectId: 'fixmyarea-capstone',
    storageBucket: 'fixmyarea-capstone.firebasestorage.app',
    iosBundleId: 'com.example.fixMyArea',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD09mYEpHavbNBuD20YZSilcfvVEUHppRo',
    appId: '1:978477640072:android:44e011f271fe639b48b23d',
    messagingSenderId: '978477640072',
    projectId: 'fixmyarea-capstone',
    storageBucket: 'fixmyarea-capstone.firebasestorage.app',
  );

}