name: fix_my_area
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  google_fonts: ^6.2.1

  firebase_core: ^2.32.0
  firebase_auth: ^4.20.0

  cloud_firestore: ^4.17.5

  intl: ^0.19.0

  google_maps_flutter: ^2.6.1
  geolocator: ^12.0.0

  url_launcher: ^6.3.0

  image_picker: ^1.1.2
  firebase_storage: ^11.7.7

  cupertino_icons: ^1.0.6

  shared_preferences: ^2.2.3
  smooth_page_indicator: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true


flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png"
  adaptive_icon_background: "#1B5E20"
  adaptive_icon_foreground: "assets/icons/app_icon.png"
